use crate::models::ZshOption;

const ZSH_REFERENCE_MANUAL_BASE: &str = "https://zsh.sourceforge.io/Doc/Release/Options.html";

pub fn get_all_options() -> Vec<ZshOption> {
    vec![
        // Global options
        ZshOption {
            name: "AUTOCD".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If a command is issued that cant be executed as a normal command, and the command is the name of a directory, perform the cd command to that directory.".to_string(),
            documentation_url: format!("{}#index-AUTOCD", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "AUTO_LIST".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "On ambiguous completions, automatically list choices when the completion function is called twice in succession.".to_string(),
            documentation_url: format!("{}#index-AUTO_LIST", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "AUTO_MENU".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "On ambiguous completions, automatically show the menu when the completion function is called twice in succession.".to_string(),
            documentation_url: format!("{}#index-AUTO_MENU", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "AUTO_NAME_DIRS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Any parameter that is set to the absolute name of a directory immediately becomes a name for that directory.".to_string(),
            documentation_url: format!("{}#index-AUTO_NAME_DIRS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "AUTO_PARAM_SLASH".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If a parameter is completed whose content is the name of a directory, add a trailing slash instead of a space.".to_string(),
            documentation_url: format!("{}#index-AUTO_PARAM_SLASH", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "AUTO_PUSHD".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Make cd push the old directory onto the directory stack.".to_string(),
            documentation_url: format!("{}#index-AUTO_PUSHD", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "AUTO_REMOVE_SLASH".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When the last character resulting from a completion is a slash and the next character typed is a word delimiter, remove the slash.".to_string(),
            documentation_url: format!("{}#index-AUTO_REMOVE_SLASH", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "AUTO_RESUME".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Treat single word simple commands without redirection as candidates for resumption of an existing job.".to_string(),
            documentation_url: format!("{}#index-AUTO_RESUME", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "BANG_HIST".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Perform textual history expansion, csh-style, treating the character ! specially.".to_string(),
            documentation_url: format!("{}#index-BANG_HIST", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "BARE_GLOB_QUAL".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "In a glob pattern, treat a trailing set of parentheses as a qualifier list, if it contains no |, ( or (if special) ~ characters.".to_string(),
            documentation_url: format!("{}#index-BARE_GLOB_QUAL", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "BASH_AUTO_LIST".to_string(),
            scope: "BOURNEOPT".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "On ambiguous completions, automatically list choices when the completion function is called twice in succession.".to_string(),
            documentation_url: format!("{}#index-BASH_AUTO_LIST", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "BEEP".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Beep on error in line editor.".to_string(),
            documentation_url: format!("{}#index-BEEP", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "BRACE_CCL".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Expand expressions in braces which would not otherwise be expanded as glob patterns to their individual characters.".to_string(),
            documentation_url: format!("{}#index-BRACE_CCL", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "BSD_ECHO".to_string(),
            scope: "BOURNEOPT".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Make the echo builtin compatible with the BSD man page echo(1) command.".to_string(),
            documentation_url: format!("{}#index-BSD_ECHO", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CDABLE_VARS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If the argument to a cd command (or an implied cd with the AUTO_CD option set) is not a directory, and does not begin with a slash, try to expand the expression as if it were preceded by a ~.".to_string(),
            documentation_url: format!("{}#index-CDABLE_VARS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CD_SILENT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Never print the working directory after a cd (even with AUTO_CD).".to_string(),
            documentation_url: format!("{}#index-CD_SILENT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CHASE_DOTS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When changing to a directory containing a path segment .. which would otherwise be treated as referring to the parent directory (i.e. a path segment .. is immediately followed by another /), resolve the path to the physical directory.".to_string(),
            documentation_url: format!("{}#index-CHASE_DOTS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CHASE_LINKS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Resolve symbolic links to their true values when changing directories.".to_string(),
            documentation_url: format!("{}#index-CHASE_LINKS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CHECK_JOBS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Print a warning message when a job is started if there are stopped jobs.".to_string(),
            documentation_url: format!("{}#index-CHECK_JOBS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CLOBBER".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Allows > redirection to truncate existing files, and >> to create files. Otherwise >! or >| must be used to truncate a file, and >>! or >>| to create a file.".to_string(),
            documentation_url: format!("{}#index-CLOBBER", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "COMPLETE_ALIASES".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Prevent aliases on the command line from being internally substituted before completion is attempted.".to_string(),
            documentation_url: format!("{}#index-COMPLETE_ALIASES", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "COMPLETE_IN_WORD".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "If unset, the cursor is taken to the end of the word if completion is started. Otherwise it stays there and completion is done from both ends.".to_string(),
            documentation_url: format!("{}#index-COMPLETE_IN_WORD", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CORRECT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Try to correct the spelling of commands.".to_string(),
            documentation_url: format!("{}#index-CORRECT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CORRECT_ALL".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Try to correct the spelling of all arguments in a line.".to_string(),
            documentation_url: format!("{}#index-CORRECT_ALL", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CSH_JUNKIE_HISTORY".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "A history reference without an event specifier will always use the previous command.".to_string(),
            documentation_url: format!("{}#index-CSH_JUNKIE_HISTORY", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CSH_JUNKIE_LOOPS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Allow loop bodies to take the form list; end instead of do list; done.".to_string(),
            documentation_url: format!("{}#index-CSH_JUNKIE_LOOPS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CSH_JUNKIE_QUOTES".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Changes the rules for single-quote escaping (see Quoting) and prevents characters from being quoted in pairs.".to_string(),
            documentation_url: format!("{}#index-CSH_JUNKIE_QUOTES", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "CSH_NULLCMD".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Do not use the values of NULLCMD and READNULLCMD when running redirections with no command.".to_string(),
            documentation_url: format!("{}#index-CSH_NULLCMD", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "DIRSTACKSIZE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "integer".to_string(),
            default: Some("8".to_string()),
            description: "The maximum size of the directory stack, by default there is no limit.".to_string(),
            documentation_url: format!("{}#index-DIRSTACKSIZE", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "DOT_GLOB".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Include filenames beginning with a . in the results of filename expansion.".to_string(),
            documentation_url: format!("{}#index-DOT_GLOB", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "EQUALS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Perform = filename expansion.".to_string(),
            documentation_url: format!("{}#index-EQUALS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "ERR_EXIT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If a command has a non-zero exit status, execute the ZERR trap, if set, and exit.".to_string(),
            documentation_url: format!("{}#index-ERR_EXIT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "EXEC".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Execute commands. When unset, commands are read and checked for syntax errors, but not executed.".to_string(),
            documentation_url: format!("{}#index-EXEC", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "EXTENDED_GLOB".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Treat the #, ~ and ^ characters as part of patterns for filename generation, etc.".to_string(),
            documentation_url: format!("{}#index-EXTENDED_GLOB", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "EXTENDED_HISTORY".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Save each commands beginning timestamp and the duration to the history file.".to_string(),
            documentation_url: format!("{}#index-EXTENDED_HISTORY", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "FLOW_CONTROL".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Allows this shell to use the default flow-control mechanism. If unset, the shell will ignore attempts to use flow control.".to_string(),
            documentation_url: format!("{}#index-FLOW_CONTROL", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "GLOB".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Perform filename generation (globbing).".to_string(),
            documentation_url: format!("{}#index-GLOB", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "GLOB_COMPLETE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When the current word has a glob pattern, do not insert all the words resulting from the glob into the command line all at once; instead, expand the glob as soon as a completion is attempted, and set up the menu completion so that one can cycle through the matches.".to_string(),
            documentation_url: format!("{}#index-GLOB_COMPLETE", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "GLOB_DOTS".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Do not require a leading . in a filename to be matched explicitly.".to_string(),
            documentation_url: format!("{}#index-GLOB_DOTS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "GLOB_STAR_SHORT".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When using the ** or *** glob patterns in a filename generation pattern, treat a trailing / after the pattern as implying ** instead of just one level of directories.".to_string(),
            documentation_url: format!("{}#index-GLOB_STAR_SHORT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "GLOB_SUBST".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Perform filename generation (globbing) on the right hand side of parameter substitutions.".to_string(),
            documentation_url: format!("{}#index-GLOB_SUBST", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HASH_CMDS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Note the location of each command the first time it is executed. Subsequent invocations of the same command will use the saved location, avoiding a path search.".to_string(),
            documentation_url: format!("{}#index-HASH_CMDS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HASH_DIRS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Whenever a command name is hashed, hash the directory containing it, as well as all directories that appear earlier in the path.".to_string(),
            documentation_url: format!("{}#index-HASH_DIRS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HASH_LIST_ALL".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Whenever a command completion is attempted, make sure the entire list of commands in the path is hashed first.".to_string(),
            documentation_url: format!("{}#index-HASH_LIST_ALL", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_ALLOW_CLOBBER".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Add | to output redirections in the history.".to_string(),
            documentation_url: format!("{}#index-HIST_ALLOW_CLOBBER", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_BEEP".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Beep in ZLE when a widget attempts to access a history entry which isnt there.".to_string(),
            documentation_url: format!("{}#index-HIST_BEEP", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_EXPIRE_DUPS_FIRST".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If the internal history needs to be trimmed to add the current command line, setting this option will cause the oldest history event that has a duplicate to be lost before losing a unique event from the list.".to_string(),
            documentation_url: format!("{}#index-HIST_EXPIRE_DUPS_FIRST", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_FIND_NO_DUPS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When searching for history entries in the line editor, do not display duplicates of a line previously found, even if the duplicates are not contiguous.".to_string(),
            documentation_url: format!("{}#index-HIST_FIND_NO_DUPS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_IGNORE_ALL_DUPS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If a new command line being added to the history list duplicates an older one, the older command is removed from the list (even if it is not the previous event).".to_string(),
            documentation_url: format!("{}#index-HIST_IGNORE_ALL_DUPS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_IGNORE_DUPS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Do not enter command lines into the history list if they are duplicates of the previous event.".to_string(),
            documentation_url: format!("{}#index-HIST_IGNORE_DUPS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_IGNORE_SPACE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Remove command lines from the history list when the first character on the line is a space, or when one of the expanded aliases contains a leading space.".to_string(),
            documentation_url: format!("{}#index-HIST_IGNORE_SPACE", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_LEX_WORDS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "By default, shell history that is read in from files is split into words on all whitespace (and tabs and newlines are converted to spaces).".to_string(),
            documentation_url: format!("{}#index-HIST_LEX_WORDS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_NO_FUNCTIONS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Remove function definitions from the history list.".to_string(),
            documentation_url: format!("{}#index-HIST_NO_FUNCTIONS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_NO_STORE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Remove the history command (fc -l) from the history list when invoked.".to_string(),
            documentation_url: format!("{}#index-HIST_NO_STORE", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_REDUCE_BLANKS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Remove superfluous blanks from each command line being added to the history list.".to_string(),
            documentation_url: format!("{}#index-HIST_REDUCE_BLANKS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_SAVE_BY_COPY".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When writing out the history file, by default zsh uses ad-hoc file locking to avoid known problems with locking on some operating systems.".to_string(),
            documentation_url: format!("{}#index-HIST_SAVE_BY_COPY", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_SAVE_NO_DUPS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When writing out the history file, older commands that duplicate newer ones are omitted.".to_string(),
            documentation_url: format!("{}#index-HIST_SAVE_NO_DUPS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HIST_VERIFY".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When the user invokes a history line, the result is loaded into the editing buffer, and the cursor is left at the end. The user can then modify the command as necessary before executing it.".to_string(),
            documentation_url: format!("{}#index-HIST_VERIFY", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HISTORY_IGNORE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "string".to_string(),
            default: None,
            description: "This variable can be set to a pattern to match command lines that should not be added to the history list.".to_string(),
            documentation_url: format!("{}#index-HISTORY_IGNORE", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "HUP".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Send the HUP signal to running jobs when the shell exits.".to_string(),
            documentation_url: format!("{}#index-HUP", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "IGNORE_BRACES".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Do not perform brace expansion.".to_string(),
            documentation_url: format!("{}#index-IGNORE_BRACES", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "IGNORE_EOF".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Do not exit on end-of-file. Require ten consecutive EOF characters to exit the shell.".to_string(),
            documentation_url: format!("{}#index-IGNORE_EOF", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "INC_APPEND_HISTORY".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "This option works like APPEND_HISTORY except that new history lines are added to the $HISTFILE incrementally (as soon as they are entered), rather than waiting until the shell exits.".to_string(),
            documentation_url: format!("{}#index-INC_APPEND_HISTORY", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "INTERACTIVE_COMMENTS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Allow comments even in interactive shells.".to_string(),
            documentation_url: format!("{}#index-INTERACTIVE_COMMENTS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "KSH_ARRAYS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Emulate ksh array handling, whereby an array element is referenced by array[index] instead of array[index].".to_string(),
            documentation_url: format!("{}#index-KSH_ARRAYS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "KSH_AUTOLOAD".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "This option makes autoloading of functions equivalent to loading the function with the source command.".to_string(),
            documentation_url: format!("{}#index-KSH_AUTOLOAD", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "KSH_GLOB".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "In pattern matching, the interpretation of parentheses is affected by a preceding (, in addition to the effect of any EXTENDED_GLOB option.".to_string(),
            documentation_url: format!("{}#index-KSH_GLOB", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "KSH_OPTION_PRINT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Alters the way options settings are printed: instead of separate lists of set and unset options, all options are shown, marked on or off to indicate whether they are set.".to_string(),
            documentation_url: format!("{}#index-KSH_OPTION_PRINT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "KSH_TYPESET".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "This option is now obsolete: a left parenthesis that introduces a type conversion in an arithmetic expression is no longer special.".to_string(),
            documentation_url: format!("{}#index-KSH_TYPESET", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "KSH_ZERO_SUBSCRIPT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Treats subscript 0 of an associative array as referring to the key rather than the element, if the key is a string.".to_string(),
            documentation_url: format!("{}#index-KSH_ZERO_SUBSCRIPT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "LIST_AMBIGUOUS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "This option works with AUTO_LIST and BASH_AUTO_LIST. If there is an unambiguous prefix or suffix shown when AUTO_LIST is set, display the rest of the list immediately.".to_string(),
            documentation_url: format!("{}#index-LIST_AMBIGUOUS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "LIST_BEEP".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Beep on an ambiguous completion. More accurately, this forces the completion widgets to return status 1 on an ambiguous completion, which causes the shell to beep if the option BEEP is also set; this may be modified if completion is called from a user-defined widget.".to_string(),
            documentation_url: format!("{}#index-LIST_BEEP", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "LIST_PACKED".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Try to make the completion list smaller (occupying less lines) by printing the matches in columns with trailing spaces.".to_string(),
            documentation_url: format!("{}#index-LIST_PACKED", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "LIST_ROWS_FIRST".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Try to make the completion list smaller by printing the matches in rows, with matches sorted horizontally.".to_string(),
            documentation_url: format!("{}#index-LIST_ROWS_FIRST", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "LIST_TYPES".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When listing files that are possible completions, show the type of each file with a trailing identifying mark.".to_string(),
            documentation_url: format!("{}#index-LIST_TYPES", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "LOCAL_OPTIONS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If set, functions created with function funcname syntax behave as though emulate -L zsh had been executed inside the function body.".to_string(),
            documentation_url: format!("{}#index-LOCAL_OPTIONS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "LOCAL_TRAPS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If set, traps created with function TRAP*() syntax behave as though emulate -L zsh had been executed inside the function body.".to_string(),
            documentation_url: format!("{}#index-LOCAL_TRAPS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "LOGIN".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "This is a login shell. If this option is explicitly unset, the shell becomes a non-login shell.".to_string(),
            documentation_url: format!("{}#index-LOGIN", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "LONG_LIST_JOBS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Print job descriptions in the long format used by the jobs command.".to_string(),
            documentation_url: format!("{}#index-LONG_LIST_JOBS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "MAGIC_EQUAL_SUBST".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "All unquoted arguments of the form anything=expression that are not assignments are expanded as if they were parameter assignments.".to_string(),
            documentation_url: format!("{}#index-MAGIC_EQUAL_SUBST", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "MAIL_WARNING".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Print a warning message if a mail file has been accessed since the shell last checked.".to_string(),
            documentation_url: format!("{}#index-MAIL_WARNING", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "MARK_DIRS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Append a trailing / to all pathnames resulting from filename generation (globbing).".to_string(),
            documentation_url: format!("{}#index-MARK_DIRS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "MENU_COMPLETE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "On an ambiguous completion, instead of listing possibilities or beeping, insert the first match immediately.".to_string(),
            documentation_url: format!("{}#index-MENU_COMPLETE", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "MONITOR".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Allow job control. Set by default in interactive shells.".to_string(),
            documentation_url: format!("{}#index-MONITOR", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "MULTIOS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Perform implicit tees or cats when multiple redirections are attempted.".to_string(),
            documentation_url: format!("{}#index-MULTIOS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "NOMATCH".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "If a pattern for filename generation has no matches, print an error, instead of leaving it unchanged in the argument list.".to_string(),
            documentation_url: format!("{}#index-NOMATCH", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "NOTIFY".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Report the status of background jobs immediately, rather than waiting until just before printing a prompt.".to_string(),
            documentation_url: format!("{}#index-NOTIFY", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "NULL_GLOB".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If a pattern for filename generation has no matches, delete the pattern from the argument list instead of reporting an error.".to_string(),
            documentation_url: format!("{}#index-NULL_GLOB", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "NUMERIC_GLOB_SORT".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Sort the filenames resulting from filename generation (globbing) numerically when it makes sense, instead of using the usual alphabetic order.".to_string(),
            documentation_url: format!("{}#index-NUMERIC_GLOB_SORT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "OVERSTRIKE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Start up the ZLE in overstrike mode.".to_string(),
            documentation_url: format!("{}#index-OVERSTRIKE", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PATH_DIRS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Perform a path search even on command names with slashes in them.".to_string(),
            documentation_url: format!("{}#index-PATH_DIRS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PATH_SCRIPT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If this option is set, a script passed to the shells standard input is taken to be a pathname, and the script found at that pathname will be read and executed.".to_string(),
            documentation_url: format!("{}#index-PATH_SCRIPT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "POSIX_ALIASES".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When this option is set, reserved words are not candidates for alias expansion.".to_string(),
            documentation_url: format!("{}#index-POSIX_ALIASES", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "POSIX_BUILTINS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When this option is set the command builtin can be used to execute a builtin command that has been redefined as a function.".to_string(),
            documentation_url: format!("{}#index-POSIX_BUILTINS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "POSIX_CD".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Modifies the behavior of cd, chdir, pushd and popd commands to make them more compatible with the POSIX standard.".to_string(),
            documentation_url: format!("{}#index-POSIX_CD", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "POSIX_IDENTIFIERS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When this option is set, only the ASCII characters a to z, A to Z, 0 to 9 and _ may be used in identifiers (names of shell parameters and modules).".to_string(),
            documentation_url: format!("{}#index-POSIX_IDENTIFIERS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "POSIX_STRINGS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "This affects the way single-byte characters are matched in patterns and regular expressions.".to_string(),
            documentation_url: format!("{}#index-POSIX_STRINGS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "POSIX_TRAPS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "When this option is set, the EXIT trap is executed in the environment of the caller of the function, rather than in the environment of the function itself.".to_string(),
            documentation_url: format!("{}#index-POSIX_TRAPS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PRINT_EIGHT_BIT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Print eight bit characters literally in completion lists, etc. instead of as sequences of \\M-...".to_string(),
            documentation_url: format!("{}#index-PRINT_EIGHT_BIT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PRINT_EXIT_VALUE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Print the exit value of programs with non-zero exit status.".to_string(),
            documentation_url: format!("{}#index-PRINT_EXIT_VALUE", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PRIVILEGED".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Turn on privileged mode. Typically this is used when script is to be run as root.".to_string(),
            documentation_url: format!("{}#index-PRIVILEGED", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PROMPT_BANG".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If set, ! is treated specially in prompt expansion.".to_string(),
            documentation_url: format!("{}#index-PROMPT_BANG", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PROMPT_CR".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Print a carriage return just before printing a prompt in the line editor.".to_string(),
            documentation_url: format!("{}#index-PROMPT_CR", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PROMPT_PERCENT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "If set, % is treated specially in prompt expansion.".to_string(),
            documentation_url: format!("{}#index-PROMPT_PERCENT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PROMPT_SP".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Attempt to preserve some screen state when a partial line is redrawn.".to_string(),
            documentation_url: format!("{}#index-PROMPT_SP", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PROMPT_SUBST".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If set, parameter expansion, command substitution and arithmetic expansion are performed in prompts.".to_string(),
            documentation_url: format!("{}#index-PROMPT_SUBST", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PUSHD_IGNORE_DUPS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Dont push multiple copies of the same directory onto the directory stack.".to_string(),
            documentation_url: format!("{}#index-PUSHD_IGNORE_DUPS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PUSHD_MINUS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Exchanges the meanings of + and - when used with a number to specify a directory in the stack.".to_string(),
            documentation_url: format!("{}#index-PUSHD_MINUS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PUSHD_SILENT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Do not print the directory stack after pushd or popd.".to_string(),
            documentation_url: format!("{}#index-PUSHD_SILENT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "PUSHD_TO_HOME".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Have pushd with no arguments act like pushd $HOME.".to_string(),
            documentation_url: format!("{}#index-PUSHD_TO_HOME", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "RC_EXPAND_PARAM".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Array expansions of the form foo${xx}bar, where the parameter xx is set to (a b c), are substituted with fooabar foobbar foocbar instead of the default fooa b cbar.".to_string(),
            documentation_url: format!("{}#index-RC_EXPAND_PARAM", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "RC_QUOTES".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Allow the character sequence  to signify a single quote within singly quoted strings.".to_string(),
            documentation_url: format!("{}#index-RC_QUOTES", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "REC_EXACT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "In completion, recognize exact matches even if they are ambiguous.".to_string(),
            documentation_url: format!("{}#index-REC_EXACT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "RESTRICTED".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Enables restricted mode. This is neither completely nor correctly implemented yet.".to_string(),
            documentation_url: format!("{}#index-RESTRICTED", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "RM_STAR_SILENT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Do not query the user before executing rm * or rm path/.".to_string(),
            documentation_url: format!("{}#index-RM_STAR_SILENT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "RM_STAR_WAIT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If querying the user before executing rm * or rm path/, first wait ten seconds and ignore anything typed in that time.".to_string(),
            documentation_url: format!("{}#index-RM_STAR_WAIT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "SH_FILE_EXPANSION".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Perform filename expansion (e.g., ~ expansion) on the right hand side of parameter assignments.".to_string(),
            documentation_url: format!("{}#index-SH_FILE_EXPANSION", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "SH_GLOB".to_string(),
            scope: "SH_GLOB".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Follow sh globbing rules for filename generation.".to_string(),
            documentation_url: format!("{}#index-SH_GLOB", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "SH_NULLCMD".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Do not use the values of NULLCMD and READNULLCMD when running redirections with no command.".to_string(),
            documentation_url: format!("{}#index-SH_NULLCMD", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "SH_OPTION_LETTERS".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If this option is set the shell tries to interpret single letter options (see Single Letter Options) used by the set command as if they were sh options.".to_string(),
            documentation_url: format!("{}#index-SH_OPTION_LETTERS", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "SH_WORD_SPLIT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Causes field splitting to be performed on unquoted parameter expansions.".to_string(),
            documentation_url: format!("{}#index-SH_WORD_SPLIT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "SINGLE_COMMAND".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If the shell is reading from standard input, it exits after a single command has been executed.".to_string(),
            documentation_url: format!("{}#index-SINGLE_COMMAND", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "SINGLE_LINE_ZLE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Use single-line command line editing instead of multi-line.".to_string(),
            documentation_url: format!("{}#index-SINGLE_LINE_ZLE", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "SUN_KEYBOARD_HACK".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If a line ends with a backslash quote key (\\), remove the backslash. If a line starts with a quote, remove it.".to_string(),
            documentation_url: format!("{}#index-SUN_KEYBOARD_HACK", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "TRANSIENT_RPROMPT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Remove the right-side prompt from the display when accepting a command line. This may be useful if terminals have problems with the right-side prompt.".to_string(),
            documentation_url: format!("{}#index-TRANSIENT_RPROMPT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "TYPESET_SILENT".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "If unset, executing any of the typeset family of commands with no options and only a parameter name will show the value of the parameter.".to_string(),
            documentation_url: format!("{}#index-TYPESET_SILENT", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "UNSET".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Treat unset parameters as if they were empty when substituting.".to_string(),
            documentation_url: format!("{}#index-UNSET", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "VERBOSE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Print shell input lines as they are read.".to_string(),
            documentation_url: format!("{}#index-VERBOSE", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "WARN_CREATE_GLOBAL".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Print a warning message when a global parameter is created in a function by an assignment or in math evaluation.".to_string(),
            documentation_url: format!("{}#index-WARN_CREATE_GLOBAL", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "WARN_NESTED_VAR".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Print a warning message when an existing parameter from an enclosing scope is assigned to in a function, or when a variable is assigned to in a function and a parameter with the same name exists in an enclosing scope.".to_string(),
            documentation_url: format!("{}#index-WARN_NESTED_VAR", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "XTRACE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("off".to_string()),
            description: "Print commands and their arguments as they are executed.".to_string(),
            documentation_url: format!("{}#index-XTRACE", ZSH_REFERENCE_MANUAL_BASE),
        },
        ZshOption {
            name: "ZLE".to_string(),
            scope: "GLOBAL".to_string(),
            r#type: "boolean".to_string(),
            default: Some("on".to_string()),
            description: "Use the Zsh Line Editor. Set by default in interactive shells.".to_string(),
            documentation_url: format!("{}#index-ZLE", ZSH_REFERENCE_MANUAL_BASE),
        },
    ]
}

pub fn filter_options(options: &[ZshOption], search_term: Option<&str>, scope: Option<&str>) -> Vec<ZshOption> {
    let mut filtered = options.to_vec();
    
    if let Some(term) = search_term {
        let term_lower = term.to_lowercase();
        filtered.retain(|opt| {
            opt.name.to_lowercase().contains(&term_lower) ||
            opt.description.to_lowercase().contains(&term_lower)
        });
    }
    
    if let Some(scope_filter) = scope {
        filtered.retain(|opt| opt.scope == scope_filter);
    }
    
    filtered
}

